name: Build Android Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Geode mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: AlwaysWavePulse-Android64
          path: ${{ steps.build.outputs.build-output }}/*.geode
